# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ITEM" ("id" VARCHAR GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"itemName" VARCHAR NOT NULL,"itemColour" VARCHAR NOT NULL);

# --- !Downs

drop table "ITEM";

